### ISSUE TITLE
Add Topics Collector

### ISSUE THREAD

**Issue by jeqo** [sysco-middleware/kafka-interceptors#10]
Would be great to have also Topics where a client push/pull data to/from.

**Comment by jeqo** [comment]
CC @timurgen

**Comment by timurgen** [comment]
@jeqo we can simply extract topic name in onSend() function, but this is a bit late, configs are sent before first onSend

**Comment by jeqo** [comment]
Agree. Do you think is worth it to do it in another Interceptor?

**Comment by jeqo** [comment]
Maybe finding a way to publish only once, or in the first "onSend" could be enough, but topics could be different between one send and another.

Also, this is probably covered already by the `zipkin` interceptor but could be interesting to have this data independent from tracing (e.g. if you don't plan to have tracing enabled in the short term but you need map between client/topic).

**Comment by timurgen** [comment]
@jeqo  if topics are subject to change then we may check it with every onSend against list of "already seen" topics. Then we may publish this data as addition to client config (and we also need a kind of logic to retrieve all these supplement messages in config collector). This approach will also involve some overhead which will increase with number of different topics.

**Comment by jeqo** [comment]
Thinking about this twice, it should be out of the `client-config` responsibility to deal with topics. It could be another interceptor or leave this to zipkin interceptor as it handles this already.
