### ISSUE TITLE
Add Benchmark to Interceptors

### ISSUE THREAD

**Issue by jeqo** [sysco-middleware/kafka-interceptors#5]
Create a project to run benchmarks.

**Comment by timurgen** [comment]
@jeqo  do we actually need it? 
Interceptors method  that run on every send/consume record are empty and only return their input parameters back. 

They consists of only two bytecode instructions
![bilde](https://user-images.githubusercontent.com/2380960/45738570-278f1100-bbf1-11e8-87f8-dd6bb9f9f295.png)

and is being inlined so method call will not be emitted at all and will not have any overhead
![bilde](https://user-images.githubusercontent.com/2380960/45738640-5311fb80-bbf1-11e8-83a8-c55b82411e01.png)

**Comment by jeqo** [comment]
It will be to gain experience with JMH and also use it for other interceptors (e.g. zipkin) and recognize the impact.

**Comment by jeqo** [comment]
Solved by #6
